"""Analysis: marginal value of an extra rolled die for a Shosuro Actor
5th Dan character.

Reads two precomputed Monte Carlo tables from ``app/data/`` -
``probabilities.prob`` (mean of ``XkY`` rolls, plus tail probabilities)
and ``shosuro_5th_dan.shosuro_lowest_3_avg`` (mean sum of the lowest
three of ``rolled`` dice) - and combines them into per-row deltas
showing what the player gains in their roll average and what they
lose (or gain) in their Shosuro bonus when they add one more rolled
die to the pool.

Both tables exist for ``reroll_tens`` True and False, so the output
covers both regimes. The CSV holds full 4-decimal precision; the
Markdown round to 2.

Run from the repo root:

    PYTHONPATH=. python3 analysis/shosuro_fifth_dan_bonuses.py

Writes three files next to the script:

  * ``ShosuroFifthDan.csv``  - machine-readable, 4-decimal precision.
  * ``ShosuroFifthDan.md``   - GitHub-renderable Markdown tables.
  * stdout                   - same as the Markdown file.
"""

import csv
import pathlib

from app.data.probabilities import prob
from app.data.shosuro_5th_dan import shosuro_lowest_3_avg


# In-game cap: the L7R rule converts overflow rolled dice into kept
# dice ("rolled > 10 -> kept += rolled - 10; rolled = 10"), so we
# never actually roll more than ten. The "+1 rolled" columns are
# blank for the rolled=10 row because adding another rolled die
# isn't a thing the game lets you do.
ROLLED_CAP = 10

# Kept range: 2..10 covers every interesting pool. Kept=1 is rare
# enough in L7R to omit; it's available in the prob table if needed.
KEPT_RANGE = range(2, 11)

# Output paths (next to this script).
HERE = pathlib.Path(__file__).resolve().parent
CSV_PATH = HERE / "ShosuroFifthDan.csv"
MD_PATH = HERE / "ShosuroFifthDan.md"

MD_INTRO = """\
# Shosuro Actor 5th Dan: marginal value of an extra rolled die

For each `(rolled, kept)` dice pool the table below shows:

- **avg roll** - the mean of an `XkY` roll.
- **Shosuro avg bonus** - the mean sum of the lowest three rolled
  dice (the Shosuro Actor 5th Dan bonus). For `rolled < 3` the
  "lowest 3" rule degenerates to "all of them", so the bonus equals
  the average sum of all rolled dice.
- **gain from +1k0** - how much the average roll goes up if you add
  one more rolled die to the pool (kept fixed).
- **Shosuro change per +1 rolled** - signed delta on the Shosuro
  bonus from adding one rolled die. Positive = the bonus goes UP
  (only happens on the `rolled = 2 -> 3` transition). Negative =
  the bonus goes DOWN, the usual case.
- **net +1k0** - sum of the previous two columns. The expected
  total swing in your result from adding `+1k0` when the Shosuro
  5th Dan ability is in play.

The `rolled = 10` rows have no `+1k0` columns: the L7R overflow
rule (`rolled > 10 -> kept += overflow`) prevents an 11th rolled
die. See `analysis/ShosuroFifthDanBonusesByPercentile.md` for the
distributional spread (10th / 50th / 90th percentile) of the same
quantities.

Generated by `analysis/shosuro_fifth_dan_bonuses.py` from the
precomputed Monte Carlo tables in `app/data/`.
"""


def avg_roll(reroll, rolled, kept):
    """Mean of an ``XkY`` roll. Returns ``None`` if the pair isn't in
    the precomputed table."""
    return prob[reroll].get((rolled, kept))


def shosuro_bonus(reroll, rolled):
    """Mean Shosuro 5th Dan bonus (sum of the lowest three rolled
    dice) for a pool of ``rolled`` dice.

    For ``rolled >= 3`` the precomputed Monte Carlo table applies.
    For ``rolled < 3`` the "lowest 3" rule degenerates to "lowest
    ``rolled``" = "all of them", so the bonus equals the average
    sum of ``rolled`` dice - which we already have in the prob
    table at ``(rolled, rolled)`` (keep them all).
    """
    if rolled >= 3:
        return shosuro_lowest_3_avg[reroll].get(rolled)
    return prob[reroll].get((rolled, rolled))


def build_rows():
    """One row per (reroll, rolled, kept) cell with the four
    derived metrics. The ``+1 rolled`` deltas are ``None`` on the
    rolled=10 row (no in-game way to add an 11th rolled die)."""
    rows = []
    for reroll in (True, False):
        for kept in KEPT_RANGE:
            for rolled in range(kept, ROLLED_CAP + 1):
                ar = avg_roll(reroll, rolled, kept)
                sh = shosuro_bonus(reroll, rolled)
                if rolled < ROLLED_CAP:
                    ar_next = avg_roll(reroll, rolled + 1, kept)
                    sh_next = shosuro_bonus(reroll, rolled + 1)
                    gain = (ar_next - ar) if ar_next is not None else None
                    # Signed delta: positive = bonus goes UP (only
                    # happens on the 2->3 transition, where the
                    # "lowest 3" cap finally engages); negative =
                    # bonus goes DOWN, the usual case.
                    sh_change = (
                        (sh_next - sh)
                        if (sh is not None and sh_next is not None)
                        else None
                    )
                    net = (
                        (gain + sh_change)
                        if (gain is not None and sh_change is not None)
                        else None
                    )
                else:
                    gain = sh_change = net = None
                rows.append({
                    "reroll": reroll,
                    "rolled": rolled,
                    "kept": kept,
                    "avg_roll": ar,
                    "shosuro_bonus": sh,
                    "gain_from_plus_1k0": gain,
                    "shosuro_change": sh_change,
                    "net_plus_1k0": net,
                })
    return rows


def write_csv(rows, path):
    def fmt(v):
        return "" if v is None else f"{v:.4f}"
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow([
            "reroll_tens", "rolled", "kept",
            "avg_roll", "shosuro_avg_bonus",
            "gain_from_plus_1k0", "shosuro_change_per_plus_1_rolled",
            "net_plus_1k0",
        ])
        for r in rows:
            w.writerow([
                str(r["reroll"]), r["rolled"], r["kept"],
                fmt(r["avg_roll"]), fmt(r["shosuro_bonus"]),
                fmt(r["gain_from_plus_1k0"]), fmt(r["shosuro_change"]),
                fmt(r["net_plus_1k0"]),
            ])


def format_markdown(rows):
    """Return the full Markdown document - intro + both per-reroll
    tables - as a single string. Used for both the file write and
    stdout, so they stay in lockstep."""
    out = [MD_INTRO]
    for reroll in (True, False):
        title = "Rerolling 10s" if reroll else "NOT rerolling 10s"
        out.append(f"\n## {title}\n")
        out.append(
            "| rolled | kept | avg roll | Shosuro avg bonus | "
            "gain from +1k0 | Shosuro change per +1 rolled | net +1k0 |"
        )
        out.append(
            "|-------:|-----:|---------:|------------------:|"
            "---------------:|-----------------------------:|---------:|"
        )
        for r in rows:
            if r["reroll"] != reroll:
                continue
            def f2(v, signed=False):
                if v is None:
                    return "—"
                return f"{v:+.2f}" if signed else f"{v:.2f}"
            out.append(
                f"| {r['rolled']} | {r['kept']} | "
                f"{f2(r['avg_roll'])} | {f2(r['shosuro_bonus'])} | "
                f"{f2(r['gain_from_plus_1k0'], signed=True)} | "
                f"{f2(r['shosuro_change'], signed=True)} | "
                f"{f2(r['net_plus_1k0'], signed=True)} |"
            )
    return "\n".join(out) + "\n"


def write_markdown(rows, path):
    path.write_text(format_markdown(rows))


def main():
    rows = build_rows()
    write_csv(rows, CSV_PATH)
    write_markdown(rows, MD_PATH)
    print(f"wrote {CSV_PATH}")
    print(f"wrote {MD_PATH}")
    print(f"({len(rows)} data rows)")
    print(format_markdown(rows))


if __name__ == "__main__":
    main()
