"""Monte Carlo percentile analysis for Shosuro Actor 5th Dan.

Companion to ``shosuro_fifth_dan_bonuses.py``. Where that script reads
the precomputed mean tables, this one runs a fresh simulation to
capture the *spread* of outcomes - the 10th / 50th / 90th percentiles
of each quantity. The Shosuro 5th Dan bonus is one of the swingier
5th-Dan abilities in the system (anywhere from +3 on a 3k3 of all 1s
up to ~+40 when both 10s in a 3k3 chain through to 10s themselves),
and the percentile spread is the right lens for "how reliable is this
bonus".

Per-trial structure: each trial samples ``rolled + 1`` dice (one for
the base pool, one extra for the "+1k0" comparison). The five tracked
quantities are computed on each trial and the percentiles taken at
the end:

  avg_roll        - sum of top ``kept`` of the base pool
  shosuro_bonus   - sum of bottom min(3, rolled) of the base pool
  gain_+1k0       - top-kept(full pool) - top-kept(base pool)
  shosuro_change  - bottom-3(full pool) - bottom-3(base pool)
  net_+1k0        - gain + shosuro_change, computed PER-TRIAL
                    (NOT p_x(gain) + p_x(shosuro_change), which would
                     overstate the spread since percentiles don't add)

Pairing matters: ``gain`` and ``shosuro_change`` are negatively
correlated within a trial (an extra die that bumps the roll average
is the same die that might displace the shosuro bottom-3), so the
net distribution has substantially less variance than its two
addends measured independently would suggest.

Rolled=10 rows skip the +1k0 columns - the L7R overflow rule
("rolled > 10 -> kept += overflow") prevents an 11th rolled die.

Output (all written next to this script):
  - ``ShosuroFifthDanBonusesByPercentile.csv`` - machine-readable,
    one row per (reroll, rolled, kept) with 15 numeric columns
    (5 metrics x 3 percentiles).
  - ``ShosuroFifthDanBonusesByPercentile.md`` - GitHub-renderable
    Markdown tables with the same data.
  - stdout                                     - same as the .md file.

Run from the repo root:

    PYTHONPATH=. python3 analysis/shosuro_fifth_dan_bonuses_by_percentile.py
"""

import csv
import pathlib

import numpy as np

SEED = 1337
N_TRIALS = 200_000      # matches the existing Shosuro precompute count
ROLLED_CAP = 10         # L7R overflow rule converts rolled past 10 into kept
KEPT_RANGE = range(2, 11)
PERCENTILES = (10, 50, 90)

HERE = pathlib.Path(__file__).resolve().parent
CSV_PATH = HERE / "ShosuroFifthDanBonusesByPercentile.csv"
MD_PATH = HERE / "ShosuroFifthDanBonusesByPercentile.md"

MD_INTRO = f"""\
# Shosuro Actor 5th Dan: distributional spread of the marginal value

Companion to `ShosuroFifthDan.md`, which shows means. This file
shows the **10th / 50th / 90th percentile** of each quantity, so
you can see how reliable (or swingy) each effect is. Each cell
reads `p10 / p50 / p90`.

For each `(rolled, kept)` dice pool the table below shows:

- **avg roll** - spread of the `XkY` roll.
- **Shosuro bonus** - spread of the Shosuro Actor 5th Dan bonus
  (sum of the lowest three rolled dice; or all of them when
  `rolled < 3`).
- **gain from +1k0** - spread of `top-kept(N+1 dice) - top-kept(N dice)`,
  measured on the same trial.
- **Shosuro change per +1 rolled** - spread of the same delta on
  the Shosuro bonus. Hard ceiling at 0 for `rolled >= 3` (extra
  die either displaces something low or does nothing).
- **net +1k0** - sum of the previous two columns, **computed per
  trial** (NOT `p_x(gain) + p_x(shosuro_change)`, which doesn't
  add for percentiles). Pairing matters: the two effects are
  negatively correlated within a trial, so the net spread is
  tighter than independent addition would suggest.

The `rolled = 10` rows have no `+1k0` columns: the L7R overflow
rule (`rolled > 10 -> kept += overflow`) prevents an 11th rolled
die.

All values are integers. This is not a rounding artifact - dice
sums are integer-valued, and at {N_TRIALS:,} trials per cell the
sample at any percentile rank is essentially always equal to its
neighbors, so the percentile lands on an actual observed integer
(`np.percentile(..., method='nearest')`).

Generated by `analysis/shosuro_fifth_dan_bonuses_by_percentile.py`
with {N_TRIALS:,} trials per cell, seed = {SEED}.
"""


def simulate_dice(rng, n_dice, reroll_tens, n_trials):
    """Sample n_trials x n_dice independent L7R dice. Returns an
    int64 array of shape (n_trials, n_dice) where each entry is the
    final summed value (post-reroll-chain when ``reroll_tens`` is
    on). Vectorized across trials for speed."""
    values = rng.integers(1, 11, size=(n_trials, n_dice)).astype(np.int64)
    if reroll_tens:
        active = values == 10
        # Each iteration adds a new die to chains still active. The
        # 50-iter ceiling is a safety bound; P(50 consecutive 10s on
        # the same die) < 10^-50 so we never actually hit it.
        for _ in range(50):
            if not active.any():
                break
            new = rng.integers(1, 11, size=values.shape).astype(np.int64)
            values = values + np.where(active, new, 0)
            active = active & (new == 10)
    return values


def simulate_cell(rng, reroll, rolled, kept, n_trials):
    """Returns a dict of per-trial int64 arrays for one
    (reroll, rolled, kept) cell. ``gain``, ``sh_change``, ``net``
    are absent when rolled == ROLLED_CAP."""
    has_extra = rolled < ROLLED_CAP
    n_total = rolled + (1 if has_extra else 0)
    dice = simulate_dice(rng, n_total, reroll, n_trials)
    # Base pool = first ``rolled`` dice. Since draws are i.i.d. this
    # is a uniformly random subset of size ``rolled`` from the full
    # ``rolled+1`` pool - no shuffle needed.
    base = dice[:, :rolled]
    base_desc = -np.sort(-base, axis=1)
    base_asc = np.sort(base, axis=1)
    base_roll = base_desc[:, :kept].sum(axis=1)
    base_shosuro = base_asc[:, :min(3, rolled)].sum(axis=1)
    out = {"avg_roll": base_roll, "shosuro_bonus": base_shosuro}
    if has_extra:
        full_desc = -np.sort(-dice, axis=1)
        full_asc = np.sort(dice, axis=1)
        full_roll = full_desc[:, :kept].sum(axis=1)
        full_shosuro = full_asc[:, :min(3, rolled + 1)].sum(axis=1)
        out["gain"] = full_roll - base_roll
        out["sh_change"] = full_shosuro - base_shosuro
        out["net"] = out["gain"] + out["sh_change"]
    return out


def pcts(arr):
    """Return (p10, p50, p90) of ``arr`` as ints, or
    (None, None, None) when arr is None (cell skipped).

    ``method='nearest'`` returns the actual observed value at the
    requested rank rather than linearly interpolating between
    neighbors. With 200k samples of a discrete (integer-valued)
    distribution like "sum of N d10", any two adjacent ranks are
    almost always identical, so linear interpolation degenerates
    to "always integer-valued" output that *looks* like a rounding
    bug. ``method='nearest'`` makes the integer nature explicit
    and lets us format as plain ints downstream.
    """
    if arr is None:
        return (None, None, None)
    p = np.percentile(arr, PERCENTILES, method="nearest")
    return tuple(int(x) for x in p)


def build_rows():
    rng = np.random.default_rng(SEED)
    rows = []
    for reroll in (True, False):
        for kept in KEPT_RANGE:
            for rolled in range(kept, ROLLED_CAP + 1):
                cell = simulate_cell(rng, reroll, rolled, kept, N_TRIALS)
                rows.append({
                    "reroll": reroll,
                    "rolled": rolled,
                    "kept": kept,
                    "avg_roll": pcts(cell.get("avg_roll")),
                    "shosuro_bonus": pcts(cell.get("shosuro_bonus")),
                    "gain": pcts(cell.get("gain")),
                    "sh_change": pcts(cell.get("sh_change")),
                    "net": pcts(cell.get("net")),
                })
    return rows


def write_csv(rows, path):
    def fmt(v):
        # All percentile values are int (see ``pcts``). The CSV
        # emits them as integers too - any consumer that wants
        # floats can cast trivially.
        return "" if v is None else str(v)
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        header = ["reroll_tens", "rolled", "kept"]
        for col in ("avg_roll", "shosuro_bonus",
                    "gain_from_plus_1k0",
                    "shosuro_change_per_plus_1_rolled",
                    "net_plus_1k0"):
            for p in PERCENTILES:
                header.append(f"{col}_p{p}")
        w.writerow(header)
        for r in rows:
            row = [str(r["reroll"]), r["rolled"], r["kept"]]
            for key in ("avg_roll", "shosuro_bonus",
                        "gain", "sh_change", "net"):
                for v in r[key]:
                    row.append(fmt(v))
            w.writerow(row)


def format_markdown(rows):
    """Return the full Markdown document - intro + both per-reroll
    tables - as a single string. Used for both the file write and
    stdout, so they stay in lockstep.

    Each percentile gets its own column (17 columns total per
    table). Values render as integers because the underlying
    dice-sum distributions are integer-valued and
    ``method='nearest'`` returns actual observed values.
    """
    def cell(v, signed=False):
        if v is None:
            return "—"
        return f"{v:+d}" if signed else f"{v:d}"
    # 5 metrics x 3 percentiles = 15 numeric columns, plus rolled
    # and kept. Headers stack the metric name above the p-suffix
    # via two header rows isn't supported in Markdown, so we
    # inline the metric prefix on each column to keep it readable
    # in a single header line.
    header_cols = ["rolled", "kept"]
    align_cols = ["-------:", "-----:"]
    metric_specs = [
        ("roll", False),        # avg_roll
        ("bonus", False),       # shosuro_bonus
        ("gain", True),         # gain
        ("sh chg", True),       # sh_change
        ("net", True),          # net
    ]
    for prefix, _ in metric_specs:
        for p in PERCENTILES:
            header_cols.append(f"{prefix} p{p}")
            align_cols.append("------:")
    out = [MD_INTRO]
    for reroll in (True, False):
        title = "Rerolling 10s" if reroll else "NOT rerolling 10s"
        out.append(f"\n## {title}\n")
        out.append("| " + " | ".join(header_cols) + " |")
        out.append("|" + "|".join(align_cols) + "|")
        for r in rows:
            if r["reroll"] != reroll:
                continue
            row_cells = [str(r["rolled"]), str(r["kept"])]
            for metric_key, (_, signed) in zip(
                ["avg_roll", "shosuro_bonus", "gain", "sh_change", "net"],
                metric_specs,
            ):
                for v in r[metric_key]:
                    row_cells.append(cell(v, signed=signed))
            out.append("| " + " | ".join(row_cells) + " |")
    return "\n".join(out) + "\n"


def write_markdown(rows, path):
    path.write_text(format_markdown(rows))


def main():
    rows = build_rows()
    write_csv(rows, CSV_PATH)
    write_markdown(rows, MD_PATH)
    print(f"wrote {CSV_PATH}")
    print(f"wrote {MD_PATH}")
    print(f"({len(rows)} data rows)")
    print(format_markdown(rows))


if __name__ == "__main__":
    main()
